### ISSUE TITLE
Refactor CoreService to use a DI container

### ISSUE THREAD

**Issue by RonnChyran** [SnowflakePowered/snowflake#166]
CoreService right now is a complete mess of a Singleton, perhaps we can restructure it to be a bit more flexible.

**Comment by antoligy** [comment]
DI is the right move here yeah

**Comment by antoligy** [comment]
I would suggest using Ninject: http://www.ninject.org/

**Comment by RonnChyran** [comment]
Yeah I was looking at Ninject, it's probably the way I'm going to go
