### ISSUE TITLE
Use a singleton proxy generator to take advantage of caching when generating configuration types

### ISSUE THREAD

**Issue by chyyran** [SnowflakePowered/snowflake#244]
http://kozmic.net/2009/08/25/castle-dynamic-proxy-tutorial-part-xiv-persisting-proxies/

**Comment by RonnChyran** [comment]
Will probably get this working as a Lazy<ProxyGenerator>, but hoping to get caching working as well.

**Comment by chyyran** [comment]
Fixed in #287
